FROM node:24-trixie-slim

WORKDIR /build

RUN mkdir out

COPY package.json package-lock.json /build/

RUN npm ci && \
  npx playwright install --with-deps chromium && \
  npm cache clean --force

CMD ["npx", "playwright", "test", "--config", "/build/out/playwright.config.js"]
