name: Docker

on: [push, pull_request]

jobs:
  docker:
    strategy:
      matrix:
        target: [
          "web-server",
          "build-server",
          "registry-watcher",
          "cli"
        ]
    name: Test docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "./dockerfiles/Dockerfile"
          platforms: linux/amd64
          target: ${{ matrix.target }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
